name: dart_to_js_transpiler
version: 1.0.0
author: Bohdan Ptyts <bohdanptyts@gmail.com>
homepage: https://github.com/bohdanbirdie/dart_to_js_transpiler

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  build: '>=0.12.0 <2.0.0'
  source_gen: ^0.9.5
  node_interop: ^1.0.3
  code_builder: ^3.2.1
  analyzer: '^0.39.8'
  
dev_dependencies:
  build_config: ^0.4.2
  build_test: ^0.10.0
  build_runner: ^1.10.0
  test: ^1.0.0
  grinder: ^0.8.4